// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sehwyxblppthfjlndgnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlaHd5eGJscHB0aGZqbG5kZ25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTQ4NDgsImV4cCI6MjA3NTY5MDg0OH0.p5HMPONt6UYK3mfuuZhXZbkHczCdXsu01qcRxXBt3-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});